### ISSUE TITLE
Function Test-ConfigSection is not cross validating the correct $object and $properties names values

### ISSUE THREAD

**Issue by Dods80** [jmgilman/ChocolateyPackageCreator#1]
The $objectproperties is of type [ChocolateyPackage] has a property value 'Installer'.
This 'Installer' property name is not found in the $properties array and causes the function to throw.

$properties value names are "processScript manifest remoteFiles localFiles path name shim"
$objectproperties value names are "Installer LocalFiles Manifest Name Path ProcessScript RemoteFiles Shim"

I did add an Installer = 'exe' value  as a guess to my package.psd1 file to see if that would bypass the exeception but then it threw another error
about "Error validating package configuration: Configuration is missing property ArgumentPrefix for object PackageInstaller"

because of adding an Installer property to my package.psd1 file it makes the script then execute code from
 Test-PackageConfiguration below.

switch ($property.Name) {
            Installer {
                # This property is optional
                if ($Configuration['Installer'].Count -gt 0) {
                    Test-ConfigSection -Object ([PackageInstaller]::new()) -Properties $property.Value.Keys
                }
            }

This is as far as I got trying to debug but now need help.

As a workaround I hashed out the line from the function Test-PackageConfiguration below.
#Test-ConfigSection -Object ([ChocolateyPackage]::new()) -Properties $Configuration.Keys

**Comment by jmgilman** [comment]
Can you share your configuration file and also tell me what version you're using? I plan on rewriting the validation logic at some point and using a schema instead as the current design is a bit clunky.

**Comment by Dods80** [comment]
ChocolateyPackageCreator version is 0.1.1

package.psd1
`@{
    name          = 'notepadplusplus.install'
    processScript = 'process.ps1'
    shim          = $False
    localFiles    = @(
        @{
            localPath  = 'files\ChocolateyInstall.ps1'
            importPath = 'tools\ChocolateyInstall.ps1'
        }
		@{
            localPath  = 'files\ChocolateyUnInstall.ps1'
            importPath = 'tools\ChocolateyUnInstall.ps1'
        }
		@{
            localPath  = 'files\npp.7.9.5.Installer.exe'
            importPath = 'tools\npp.7.9.5.Installer.exe'
        }
		@{
            localPath  = 'files\npp.7.9.5.Installer.x64.exe'
            importPath = 'tools\npp.7.9.5.Installer.x64.exe'
        }
    ) 
    manifest      = @{
        metadata = @{
            id                       = 'notepadplusplus.install'
            title                    = 'Notepad++ (Install)'
            version                  = '7.9.5'
            authors                  = 'Don Ho'
            owners                   = 'chocolatey-community'
            summary                  = 'Installs Notepad++'
            description              = 'Notepad++ is a free (as in "free speech" and also as in "free beer") source code editor and Notepad replacement'
            projectUrl               = 'https://notepad-plus-plus.org/'
			iconUrl                  = 'https://cdn.jsdelivr.net/gh/chocolatey-community/chocolatey-coreteampackages@8a927ff286164545446171f26f19b436622e69b5/icons/notepadplusplus.png'
            packageSourceUrl         = 'https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/notepadplusplus.install'
            tags                     = 'notepad notepadplusplus notepad-plus-plus editor text development foss'
            copyright                = '2021 Don Ho'
            licenseUrl               = 'https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/LICENSE'
            requireLicenseAcceptance = 'false'
            dependencies             = @(
			    @{
                    id      = 'chocolatey-core.extension'
                    version = '1.3.3'
                }
			)
        }
        files    = @(
            @{
                src    = 'tools\**'
                target = 'tools'
            }
        )
    }
}`

btw I extended the packagemetadata class to include the $iconurl property hense why you see it above.
I was just testing internalizing a package and used notepad++ as my test.

**Comment by jmgilman** [comment]
So, currently, the way it works is that all properties must be present in the configuration file, even if you don't plan on using them. So in the above case, you would just need to add the `installer` property:

```powershell
@{
# ...
shim = $False
installer = @{}
# ...
}
```

This is the next thing I want to address and I hope to mark some of the properties as optional and some as required.

**Comment by Dods80** [comment]
Hello Joshua,

Adding installer = @{} causes the code to throw as I mentioned in the first post.

Error validating package configuration: Configuration is missing property RemoteFiles for object ChocolateyPackage
At C:\Program Files\WindowsPowerShell\Modules\ChocolateyPackageCreator\0.1.1\functions\package.ps1:244 char:13
+             throw 'Error validating package configuration: Configurat ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error validatin...ocolateyPackage:String) [], RuntimeException
    + FullyQualifiedErrorId : Error validating package configuration: Configuration is missing property RemoteFiles fo 
   r object ChocolateyPackage

**Comment by jmgilman** [comment]
The module is telling you that you didn't define the `RemoteFiles` property in your package configuration file. The module requires that **all** properties be defined, even if they are empty. So building on my last snippet:

```powershell
@{
# ...
shim = $false
installer = @{}
remoteFiles = @()
# ...
}
```

The latest commit (95cadfb9db5b1ad8fbd98a761e9599216d2860ac) refactors the validation logic to use schema files instead of enforcing every property be present. In other words, it will allow your original script to work as you had likely expected. I will try and get a release out today and you can test it out.

**Comment by jmgilman** [comment]
The latest version (0.2.0) now implements support for optional properties. You are no longer required to define optional properties like `Installer` and `RemoteFiles` if you're not using them. Feel free to test it out and let me know if this resolves your issue.

Also, see the [schema documentation](https://github.com/jmgilman/ChocolateyPackageCreator/blob/master/docs/schema.md) for a reference of all the possible properties you can define in your package file and which ones are required.
